server:
  port: 8080
  max-http-header-size: 16000
  compression:
    enabled: true
    mime-types:
    - application/json
    min-response-size: 5120
spring:
  application:
    name:ITEM-SERVICE
  profiles:
    active:
    - local
  cache:
    type: caffeine
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
