server:
  port: 8080
  max-http-header-size: 16000
  compression:
    enabled: true
    mime-types:
    - application/json
    min-response-size: 5120
spring:
  application:
    name:ITEM-SERVICE
  profiles:
    active:
    - local
  cache:
    type: caffeine
  data:
    mongodb:
       uri: mongodb+srv://test_user:test@item-cluster.tzqgu.mongodb.net/products?retryWrites=true&w=majority
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
